### PR TITLE
Replace browserify with Rollup

### PR DESCRIPTION
**Pull request by taggon**
And many other things also have changed:
- Grunt is removed.
- Babel and ESLint settings are updated and codes are also fixed according to the new lint rules.
- Now jQuery and underscore refer to global variables.
- The production build has a null reference to `debug` module, so `debug()` function does nothing in the production. But It is still available in the development environment.

As a result of these updates, the bundle files size is reduced in a dramatic way:
- customize-dm-admin.js
  - Development: 96,558 to 23,750 bytes (24.6% of the original)
  - Production: 16,843 to 5,065 bytes (30.1%)
- customize-dm-preview.js:
  - Development: 132,595 to 33,308 bytes (25.1%)
  - Production: 22,480 to 9,099 bytes (40.5%)

### CODE REVIEW

**Comment by dzver** [comment]
Good job!

Grunt is there so that copytotheplace works, which is the automatic copying of the bundled js files to your dev WordPress plugins dir. Do you think that this isn't worth keeping? I relied on it to make my only PR but there could be other ways to achieve the same thing.

**Comment by taggon** [comment]
@dzver With this PR, you can just clone this repo under the `/wp-content/plugins` dir instead of putting it into elsewhere then copying the bundles. Subversion won't recognize that it is a git repo because of the magical `postinstall` script. ;)

**Comment by sirbrillig** [comment]
You can also use copytotheplace without grunt by just doing `copytotheplace .` manually in the repo (I like to keep my git and svn repos separate locally, but both are good choices).

**Review by sirbrillig — APPROVED** [review]
Looks good to me. Nice work!

**Pull request merged**
